# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MFyolo\ui\YOLOdetect_2.0.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1420, 716)
        self.label_left = QtWidgets.QLabel(Form)
        self.label_left.setGeometry(QtCore.QRect(10, 30, 700, 320))
        self.label_left.setObjectName("label_left")
        self.label_right = QtWidgets.QLabel(Form)
        self.label_right.setGeometry(QtCore.QRect(710, 30, 700, 320))
        self.label_right.setObjectName("label_right")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 370, 841, 141))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 111, 21))
        font = QtGui.QFont()
        font.setFamily("华光楷体一_CNKI")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.open_weight_path = QtWidgets.QLineEdit(self.groupBox)
        self.open_weight_path.setGeometry(QtCore.QRect(170, 30, 561, 20))
        self.open_weight_path.setObjectName("open_weight_path")
        self.select_weith_pth_button = QtWidgets.QPushButton(self.groupBox)
        self.select_weith_pth_button.setGeometry(QtCore.QRect(740, 30, 71, 20))
        self.select_weith_pth_button.setObjectName("select_weith_pth_button")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setGeometry(QtCore.QRect(30, 60, 681, 71))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.open_video_path = QtWidgets.QLineEdit(self.tab_2)
        self.open_video_path.setGeometry(QtCore.QRect(70, 20, 511, 20))
        self.open_video_path.setObjectName("open_video_path")
        self.open_video_button = QtWidgets.QPushButton(self.tab_2)
        self.open_video_button.setGeometry(QtCore.QRect(590, 20, 71, 20))
        self.open_video_button.setObjectName("open_video_button")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(0, 20, 111, 21))
        font = QtGui.QFont()
        font.setFamily("华光楷体一_CNKI")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_2, "")
        self.start_YOLOdetect_button = QtWidgets.QPushButton(self.groupBox)
        self.start_YOLOdetect_button.setGeometry(QtCore.QRect(730, 80, 91, 41))
        self.start_YOLOdetect_button.setObjectName("start_YOLOdetect_button")
        self.tabWidget.raise_()
        self.label_3.raise_()
        self.open_weight_path.raise_()
        self.select_weith_pth_button.raise_()
        self.start_YOLOdetect_button.raise_()
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 530, 841, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 151, 21))
        font = QtGui.QFont()
        font.setFamily("华光楷体一_CNKI")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pretrain_document_path = QtWidgets.QLineEdit(self.groupBox_2)
        self.pretrain_document_path.setGeometry(QtCore.QRect(180, 30, 561, 20))
        self.pretrain_document_path.setObjectName("pretrain_document_path")
        self.data_path = QtWidgets.QLineEdit(self.groupBox_2)
        self.data_path.setGeometry(QtCore.QRect(180, 70, 561, 20))
        self.data_path.setObjectName("data_path")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("华光楷体一_CNKI")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.select_pretrain_pth_button = QtWidgets.QPushButton(self.groupBox_2)
        self.select_pretrain_pth_button.setGeometry(QtCore.QRect(750, 30, 71, 20))
        self.select_pretrain_pth_button.setObjectName("select_pretrain_pth_button")
        self.select_vocdata_button = QtWidgets.QPushButton(self.groupBox_2)
        self.select_vocdata_button.setGeometry(QtCore.QRect(750, 70, 71, 20))
        self.select_vocdata_button.setObjectName("select_vocdata_button")
        self.start_train_button = QtWidgets.QPushButton(self.groupBox_2)
        self.start_train_button.setGeometry(QtCore.QRect(710, 110, 111, 31))
        self.start_train_button.setObjectName("start_train_button")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(870, 370, 511, 311))
        self.textEdit.setObjectName("textEdit")
        self.verticalScrollBar = QtWidgets.QScrollBar(Form)
        self.verticalScrollBar.setGeometry(QtCore.QRect(1360, 370, 20, 301))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "YoloV3训练检测平台"))
        self.label_left.setText(_translate("Form", "等待摄像头连接。。。"))
        self.label_right.setText(_translate("Form", "等待开始检测。。。"))
        self.groupBox.setTitle(_translate("Form", "检测操作区"))
        self.label_3.setText(_translate("Form", "权重文件路径："))
        self.select_weith_pth_button.setText(_translate("Form", "浏览"))
        self.pushButton_2.setText(_translate("Form", "打开摄像头"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "检测摄像头画面"))
        self.open_video_button.setText(_translate("Form", "浏览"))
        self.label_6.setText(_translate("Form", "视频路径："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "检测视频画面"))
        self.start_YOLOdetect_button.setText(_translate("Form", "开始YOLO检测"))
        self.groupBox_2.setTitle(_translate("Form", "训练操作区"))
        self.label_4.setText(_translate("Form", "预训练权重文件路径："))
        self.label_5.setText(_translate("Form", "数据集路径："))
        self.select_pretrain_pth_button.setText(_translate("Form", "浏览"))
        self.select_vocdata_button.setText(_translate("Form", "浏览"))
        self.start_train_button.setText(_translate("Form", "开始训练"))

